### ISSUE TITLE
Compiler Warnings

### ISSUE THREAD

**Issue by Karl-opec** [vdr-projects/vdr-plugin-vnsiserver#5]
Hello compiling this PLUGIN i get the following 2 Compiler warnings:

`treamer.c: In constructor cLiveStreamer::cLiveStreamer(int, bool, int, uint8_t, uint32_t):
streamer.c:57:17: warning: member ‘cLiveStreamer::m_Event’ is used uninitialized [-Wuninitialized]
   57 |  , m_VideoInput(m_Event)
      |                 ^~~~~~~
`
and

`channelfilter.c: In member function ‘void cVNSIChannelFilter::StoreWhitelist(bool)’:
channelfilter.c:188:23: warning: loop variable ‘i’ creates a copy from type ‘const cVNSIProvider’ [-Wrange-loop-construct]
  188 |       for (const auto i : *whitelist)
      |                       ^
channelfilter.c:188:23: note: use reference type to prevent copying
  188 |       for (const auto i : *whitelist)
      |                       ^
      |                       &
g++ -g -O3 -Wall -march=native -Woverloaded-virtual -Wno-parentheses -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -std=c++11 -c -D_GNU_SOURCE -DPLUGIN_NAME_I18N='"vnsiserver"' -DVNSI_SERVER_VERSION='"1.8.3"' -I/usr/src/packages/BUILD/vdr-git-2.6.3/include -o vnsitimer.o vnsitimer.c
In file included from /usr/include/c++/13/bits/shared_ptr_atomic.h:33,
                 from /usr/include/c++/13/memory:81,
                 from videoinput.h:27,
                 from videoinput.c:27:
In member function ‘std::__atomic_base<_IntTp>::__int_type std::__atomic_base<_IntTp>::load(std::memory_order) const [with _ITp = bool]’,
    inlined from ‘std::atomic<bool>::operator bool() const’ at /usr/include/c++/13/atomic:87:26,
    inlined from ‘bool cDummyReceiver::BeenDetached()’ at videoinput.c:428:31,
    inlined from ‘static std::shared_ptr<cDummyReceiver> cDummyReceiver::Create(cDevice*)’ at videoinput.c:468:28:
/usr/include/c++/13/bits/atomic_base.h:505:31: warning: ‘unsigned char __atomic_load_1(const volatile void*, int)’ writing 1 byte into a region of size 0 overflows the destination [-Wstringop-overflow=]
  505 |         return __atomic_load_n(&_M_i, int(__m));
      |                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
In static member function ‘static std::shared_ptr<cDummyReceiver> cDummyReceiver::Create(cDevice*)’:
cc1plus: note: destination object is likely at address zero
In member function ‘std::__atomic_base<_IntTp>::__int_type std::__atomic_base<_IntTp>::load(std::memory_order) const [with _ITp = bool]’,
    inlined from ‘std::atomic<bool>::operator bool() const’ at /usr/include/c++/13/atomic:87:26,
    inlined from ‘bool cDummyReceiver::BeenDetached()’ at videoinput.c:428:31,
    inlined from ‘static std::shared_ptr<cDummyReceiver> cDummyReceiver::Create(cDevice*)’ at videoinput.c:468:28:
/usr/include/c++/13/bits/atomic_base.h:505:31: warning: ‘unsigned char __atomic_load_1(const volatile void*, int)’ writing 1 byte into a region of size 0 overflows the destination [-Wstringop-overflow=]
In static member function ‘static std::shared_ptr<cDummyReceiver> cDummyReceiver::Create(cDevice*)’:
cc1plus: note: destination object is likely at address zero
`

the Plugin works at first but later i get several crashes, with following messages in syslog:

`Jan 29 22:26:53 vnas2.home.arpa vdr[24613]: [24659] VNSI: Requesting clients to reload channels list
Jan 29 22:26:54 vnas2.home.arpa runvdr.extreme[24613]: malloc(): unaligned tcache chunk detected
`
`Jan 29 22:40:27 vnas2.home.arpa vdr[5531]: [6659] VNSI: Video stream change, pid: 5101, width: 1280, height: 720, aspect: 1,777778
Jan 29 22:40:28 vnas2.home.arpa vdr[5531]: [5539] changing pids of channel 2169 (SWR RP HD) from 5131+5131=27:5132=deu@3,5133=mis@3,5137=qks@3;5136=deu@106:5135=deu:5134 to 5121+5121=27:5122=deu@3,5123=mis@3,5127=qks>
Jan 29 22:40:29 vnas2.home.arpa vdr[5531]: [5580] VNSI: Requesting clients to reload channels list
Jan 29 22:40:29 vnas2.home.arpa runvdr.extreme[5531]: malloc(): unaligned tcache chunk detected
`
Are these Warnings related to the vdr crash?

BTW vdr is 2.6.6
Compiler is g++ (SUSE Linux) 13.2.1 20240109 [revision 36ddb5230f56a30317630a928dd73ed46eda03f1]

>

**Comment by M-Reimer** [comment]
Possibly. Please create a backtrace.

**Comment by Karl-opec** [comment]
I don't know how to that?

**Comment by Karl-opec** [comment]
Perhaps 'writing 1 byte into a region of size 0 overflows the destination [-Wstringop-overflow=] '
in source gives a hint.

**Comment by wirbel-at-vdr-portal** [comment]
Aren't all of those addressed now properly at vdr-portal.de threads, such that this issue could be closed as done?
